<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        Question::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $questions = [

            // ── GENERAL KNOWLEDGE (Q1–Q8) ─────────────────────────────────────
            [
                'order_index'      => 1,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'What does NFC stand for in contactless payments?',
                'options'          => ['Near Field Communication', 'Network Financial Connection', 'New Finance Channel', 'National Fast Connectivity'],
                'correct_answer'   => 'Near Field Communication',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 2,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'Which Kenyan city is known as the "Silicon Savannah"?',
                'options'          => ['Mombasa', 'Kisumu', 'Nairobi', 'Nakuru'],
                'correct_answer'   => 'Nairobi',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 3,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'Which company owns Android?',
                'options'          => ['Samsung', 'Microsoft', 'Google', 'Apple'],
                'correct_answer'   => 'Google',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 4,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'Which is the largest ocean on Earth?',
                'options'          => ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
                'correct_answer'   => 'Pacific',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 5,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'Which Kenyan athlete won Olympic gold in the men\'s 800 metres at both London 2012 and Rio 2016?',
                'options'          => ['Emmanuel Wanyonyi', 'Ferguson Rotich', 'David Rudisha', 'Timothy Cheruiyot'],
                'correct_answer'   => 'David Rudisha',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 6,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'What does VAR stand for in football?',
                'options'          => ['Video Assistant Referee', 'Virtual Assistant Replay', 'Video Action Review', 'Verified Assistant Referee'],
                'correct_answer'   => 'Video Assistant Referee',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 7,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'Which payment technology allows a customer to simply tap their card or phone to pay?',
                'options'          => ['Magnetic Stripe', 'Contactless Payments', 'SWIFT', 'RTGS'],
                'correct_answer'   => 'Contactless Payments',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 8,
                'category'         => 'general_knowledge',
                'type'             => 'multiple_choice',
                'text'             => 'Which company sponsors the "Player of the Match" award at the FIFA World Cup?',
                'options'          => ['Coca-Cola', 'Visa', 'Adidas', 'Hyundai'],
                'correct_answer'   => 'Adidas',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],

            // ── FIFA WORLD CUP (Q9–Q16) ───────────────────────────────────────
            [
                'order_index'      => 9,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'Which country has won the FIFA World Cup the most times?',
                'options'          => ['Germany', 'Italy', 'Argentina', 'Brazil'],
                'correct_answer'   => 'Brazil',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 10,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'Which three countries are hosting the FIFA World Cup 2026?',
                'options'          => ['USA, Mexico & Canada', 'USA, Panama & Mexico', 'USA, Costa Rica & Canada', 'Canada, Brazil & USA'],
                'correct_answer'   => 'USA, Mexico & Canada',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 11,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'How many teams are participating in the FIFA World Cup 2026?',
                'options'          => ['32', '40', '48', '64'],
                'correct_answer'   => '48',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 12,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'Which country hosted the first FIFA World Cup in 1930?',
                'options'          => ['Brazil', 'Uruguay', 'Italy', 'England'],
                'correct_answer'   => 'Uruguay',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 13,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'What is the maximum duration of extra time in a knockout match?',
                'options'          => ['20 minutes', '25 minutes', '30 minutes', '40 minutes'],
                'correct_answer'   => '30 minutes',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 14,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'If a knockout match remains tied after extra time, what determines the winner?',
                'options'          => ['Golden Goal', 'Coin Toss', 'Penalty Shootout', 'Replay'],
                'correct_answer'   => 'Penalty Shootout',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 15,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'Which African nation has won the Africa Cup of Nations (AFCON) the most times?',
                'options'          => ['Cameroon', 'Nigeria', 'Egypt', 'Ghana'],
                'correct_answer'   => 'Egypt',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 16,
                'category'         => 'fifa_world_cup',
                'type'             => 'multiple_choice',
                'text'             => 'Which country has appeared in every FIFA World Cup tournament?',
                'options'          => ['Germany', 'Argentina', 'Brazil', 'Italy'],
                'correct_answer'   => 'Brazil',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],

            // ── VISA (Q17–Q24) ────────────────────────────────────────────────
            [
                'order_index'      => 17,
                'category'         => 'visa',
                'type'             => 'multiple_choice',
                'text'             => 'What is Visa Kenya\'s official social media handle?',
                'options'          => ['@visakenya254', '@visa_kenya', '@visaEA', '@visaafrica'],
                'correct_answer'   => '@visa_kenya',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 18,
                'category'         => 'visa',
                'type'             => 'multiple_choice',
                'text'             => 'How many countries and territories worldwide accept Visa?',
                'options'          => ['Over 100', 'Over 150', 'Over 200', 'Over 300'],
                'correct_answer'   => 'Over 200',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 19,
                'category'         => 'visa',
                'type'             => 'multiple_choice',
                'text'             => 'Where can you use your Visa card?',
                'options'          => ['Restaurants', 'Supermarkets', 'Online stores', 'All of the above'],
                'correct_answer'   => 'All of the above',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 20,
                'category'         => 'visa',
                'type'             => 'true_false',
                'text'             => 'True or False: The M-Pesa GlobalPay Virtual Visa Card allows Kenyans to spend globally using their M-Pesa balance.',
                'options'          => ['True', 'False'],
                'correct_answer'   => 'True',
                'duration_seconds' => 20,
                'is_double_points' => true,
            ],
            [
                'order_index'      => 21,
                'category'         => 'visa',
                'type'             => 'multiple_choice',
                'text'             => 'What technology allows Kenyan merchants to accept card payments using only a smartphone, no separate card machine required?',
                'options'          => ['QR Pay', 'Tap to Phone', 'Scan & Go', 'Mobile POS Lite'],
                'correct_answer'   => 'Tap to Phone',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 22,
                'category'         => 'visa',
                'type'             => 'multiple_choice',
                'text'             => 'Nairobi serves as Visa\'s hub for which region?',
                'options'          => ['Kenya', 'East Africa', 'Southern Africa', 'Horn of Africa'],
                'correct_answer'   => 'East Africa',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 23,
                'category'         => 'visa',
                'type'             => 'true_false',
                'text'             => 'True or False: Visa is not a bank and does not issue cards directly to customers — banks and financial institutions do.',
                'options'          => ['True', 'False'],
                'correct_answer'   => 'True',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 24,
                'category'         => 'visa',
                'type'             => 'multiple_choice',
                'text'             => 'What is the name of Visa\'s real-time payments platform that allows money to be sent directly to a Visa card, often used for instant payouts?',
                'options'          => ['Visa Direct', 'Visa Instant', 'Visa Flow', 'Visa Express'],
                'correct_answer'   => 'Visa Direct',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],

            // ── M-PESA (Q25–Q32) ──────────────────────────────────────────────
            [
                'order_index'      => 25,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'In what year was M-Pesa launched in Kenya?',
                'options'          => ['2005', '2007', '2010', '2012'],
                'correct_answer'   => '2007',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 26,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'Which company launched and operates M-Pesa in Kenya?',
                'options'          => ['Airtel', 'Safaricom', 'Equity Bank', 'KCB'],
                'correct_answer'   => 'Safaricom',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 27,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'What does the "M" in M-Pesa stand for?',
                'options'          => ['Money', 'Mobile', 'Micro', 'Modern'],
                'correct_answer'   => 'Mobile',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 28,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'What is the name of the M-Pesa facility that allows users to transact even with insufficient balance?',
                'options'          => ['Okoa Jahazi', 'M-Shwari', 'Fuliza', 'KCB M-Pesa'],
                'correct_answer'   => 'Fuliza',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 29,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'What network of physical outlets allows customers to deposit and withdraw M-Pesa cash?',
                'options'          => ['Branches', 'Agents', 'Kiosks', 'Booths'],
                'correct_answer'   => 'Agents',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 30,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'Which product lets M-Pesa customers make global payments using a virtual Visa card?',
                'options'          => ['M-Pesa World Card', 'Safaricom Travel Card', 'M-Pesa GlobalPay Virtual Visa Card', 'M-Pesa Elite Card'],
                'correct_answer'   => 'M-Pesa GlobalPay Virtual Visa Card',
                'duration_seconds' => 30,
                'is_double_points' => true,
            ],
            [
                'order_index'      => 31,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'Which app do customers use to activate and manage their M-Pesa GlobalPay Virtual Visa Card?',
                'options'          => ['M-Pesa App', 'Safaricom Neo', 'MyOne App', 'Vodafone Pay'],
                'correct_answer'   => 'MyOne App',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 32,
                'category'         => 'mpesa',
                'type'             => 'multiple_choice',
                'text'             => 'What keeps the M-Pesa GlobalPay Virtual Visa Card secure for online transactions?',
                'options'          => ['A fixed CVV printed on the card', 'A dynamic, regularly refreshed CVV', 'No CVV is required', 'Physical card swipe only'],
                'correct_answer'   => 'A dynamic, regularly refreshed CVV',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],

            // ── CAMPAIGN (Q33–Q37) ────────────────────────────────────────────
            [
                'order_index'      => 33,
                'category'         => 'campaign',
                'type'             => 'multiple_choice',
                'text'             => 'What does "Game Iko On" mean in English?',
                'options'          => ['The Match is Over', 'The Game is On', 'Football Forever', 'Play to Win'],
                'correct_answer'   => 'The Game is On',
                'duration_seconds' => 20,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 34,
                'category'         => 'campaign',
                'type'             => 'multiple_choice',
                'text'             => 'What is the exact name of the card promoted throughout the Game Iko On campaign?',
                'options'          => ['M-Pesa Visa Card', 'Safaricom World Card', 'M-Pesa GlobalPay Virtual Visa Card', 'Visa Kenya Card'],
                'correct_answer'   => 'M-Pesa GlobalPay Virtual Visa Card',
                'duration_seconds' => 30,
                'is_double_points' => true,
            ],
            [
                'order_index'      => 35,
                'category'         => 'campaign',
                'type'             => 'multiple_choice',
                'text'             => 'Where have Game Iko On activations taken place across Kenya this season?',
                'options'          => ['Malls', 'Stadiums', 'Universities', 'Online only'],
                'correct_answer'   => 'Malls',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 36,
                'category'         => 'campaign',
                'type'             => 'multiple_choice',
                'text'             => 'What is the spirit behind the Game Iko On campaign this season?',
                'options'          => [
                    'Bringing football fans together through the M-Pesa GlobalPay Virtual Visa Card',
                    'Promoting a new mobile banking app',
                    'Launching a new radio station',
                    'Celebrating Kenya\'s rugby season',
                ],
                'correct_answer'   => 'Bringing football fans together through the M-Pesa GlobalPay Virtual Visa Card',
                'duration_seconds' => 30,
                'is_double_points' => false,
            ],
            [
                'order_index'      => 37,
                'category'         => 'campaign',
                'type'             => 'multiple_choice',
                'text'             => 'Which two radio stations have carried the Game Iko On campaign this season?',
                'options'          => ['Kiss FM and Classic 105', 'Capital FM and Homeboyz Radio', 'Radio Jambo and Ghetto Radio', 'NRG Radio and Metro FM'],
                'correct_answer'   => 'Capital FM and Homeboyz Radio',
                'duration_seconds' => 25,
                'is_double_points' => false,
            ],
        ];

        foreach ($questions as $q) {
            Question::updateOrCreate(
                ['order_index' => $q['order_index']],
                array_merge($q, ['status' => 'draft', 'activated_at' => null])
            );
        }

        $this->command->info('Seeded ' . count($questions) . ' questions across 5 categories.');
    }
}
